/*
 * Portal Client API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type File struct {

	Id string `json:"id,omitempty"`

	Content string `json:"content,omitempty"`

	PublishedAt string `json:"published_at,omitempty"`
}
