/*
 * Portal Client API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Grade int32 `json:"grade,omitempty"`
}
