/*
 * Portal Client API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Course struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Year int32 `json:"year,omitempty"`

	Semester string `json:"semester,omitempty"`

	Day int32 `json:"day,omitempty"`

	Time int32 `json:"time,omitempty"`

	Location string `json:"location,omitempty"`
}
