/*
 * Portal Client API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Task struct {

	Id int64 `json:"id,omitempty"`

	Group string `json:"group,omitempty"`

	Title string `json:"title,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Status string `json:"status,omitempty"`

	Deadline string `json:"deadline,omitempty"`

	UpdateAt string `json:"update_at,omitempty"`
}
